---
title: "Projekt Optymalizacja nieliniowa"
subtitle: "Cz 2 Optymalizacja wielowymiarowa"
author: | 
  | Krawiec Piotr
  | Inżynieria i analiza danych, 3 Rok
date: "01/12/2021"
description: "Inżynieria i analiza danych, 3 Rok"
header-includes: \usepackage{animate}
output:
  beamer_presentation:
    theme: "Antibes"
    keep_tex: true
lang: pl
---

```{r setup, include=FALSE, warning=FALSE}
library(knitr)
hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    x <- c(more, x[lines], more)
  }                                                         
  # paste these lines together                              
  x <- paste(c(x, ""), collapse = "\n")                     
  hook_output(x, options)                                   
})                                                          
knitr::opts_chunk$set(echo = TRUE)                          
knitr::opts_chunk$set(cache = TRUE) 
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
Sys.setlocale("LC_ALL", "Polish")
```
# Wstęp

# Problem

```{r}
a = 1
b = 100

f <- function(x, y) {
  (a - x)^2 + b*(y - x^2)^2  
}
```

```{r}
x <- seq(-2, 2, length.out=200)
y <- seq(-1.4, 5, length.out=200)
z <- outer(x, y, f)
contour(x, y, z, nlevels=20)
```

```{r}
x <- seq(-3, 3, length.out=200)
y <- seq(-1, 3, length.out=200)
z <- outer(x, y, f)
contour(x, y, z, nlevels=20)
```

```{r}
for (i in 1:300){
 persp(x,y,z, theta=i,phi=1,expand=0.4,col = "lightblue",xlab = "X",
 ylab = "Y", zlab = "Z",ticktype = "detailed")
 Sys.sleep(0.04)
}
```